version: '2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#      - ./my_volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
    restart: always
    networks:
      default:
        aliases:
          - elastic.service
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://elastic.service:9200
